name: Data importation

on:
  # Tous les jours à 6h00 et dans les cas de push sur certaines branches.
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  import-data:
    runs-on: ubuntu-latest  # Spécifie un environnement d'exécution

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python requirements
        run: pip install -r requirements.txt

      - name: Import data
        run: python importation.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWSs_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
